# 使用Pickle序列号Numpy array

In [1]:
import pickle
import numpy as np

In [4]:
x = np.arange(10)

In [5]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
f = open('x.pkl','wb')
pickle.dump(x,f)

In [10]:
f = open('x.pkl','rb')
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.save('one_array',x)

In [13]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
y = np.arange(20)

In [15]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
np.savez('two_array.npz',a=x,b=y)

In [20]:
c = np.load('two_array.npz')

In [21]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])