# 快速创建数组

In [2]:
import numpy as np

In [3]:
np.random.randn(10)

array([-0.6542673 ,  0.7761785 , -0.55046316,  0.1468767 ,  1.93812842,
        1.51600517, -0.57108701, -2.32325764, -0.53643244, -0.21477779])

In [7]:
np.random.randint(10,size=(20)).reshape(4,5)

array([[4, 3, 0, 2, 1],
       [8, 0, 4, 5, 1],
       [0, 4, 7, 6, 6],
       [5, 8, 6, 8, 4]])

# 数组的运算

In [11]:
a = np.random.randint(10,size=(20)).reshape(4,5)

In [12]:
a

array([[5, 0, 5, 0, 6],
       [0, 2, 7, 0, 7],
       [6, 3, 3, 1, 7],
       [1, 8, 8, 9, 4]])

In [13]:
b = np.random.randint(10,size=(20)).reshape(4,5)

In [14]:
b

array([[6, 0, 7, 8, 8],
       [0, 0, 7, 6, 1],
       [1, 7, 1, 3, 8],
       [3, 9, 7, 9, 2]])

In [15]:
a + b

array([[11,  0, 12,  8, 14],
       [ 0,  2, 14,  6,  8],
       [ 7, 10,  4,  4, 15],
       [ 4, 17, 15, 18,  6]])

In [16]:
a - b

array([[-1,  0, -2, -8, -2],
       [ 0,  2,  0, -6,  6],
       [ 5, -4,  2, -2, -1],
       [-2, -1,  1,  0,  2]])

In [17]:
a * b

array([[30,  0, 35,  0, 48],
       [ 0,  0, 49,  0,  7],
       [ 6, 21,  3,  3, 56],
       [ 3, 72, 56, 81,  8]])

In [19]:
np.mat([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [20]:
np.mat(a) #将数组转换成矩阵

matrix([[5, 0, 5, 0, 6],
        [0, 2, 7, 0, 7],
        [6, 3, 3, 1, 7],
        [1, 8, 8, 9, 4]])

# 矩阵的运算

In [22]:
A = np.mat(a)
B = np.mat(b)

In [23]:
A

matrix([[5, 0, 5, 0, 6],
        [0, 2, 7, 0, 7],
        [6, 3, 3, 1, 7],
        [1, 8, 8, 9, 4]])

In [24]:
B

matrix([[6, 0, 7, 8, 8],
        [0, 0, 7, 6, 1],
        [1, 7, 1, 3, 8],
        [3, 9, 7, 9, 2]])

In [25]:
A + B

matrix([[11,  0, 12,  8, 14],
        [ 0,  2, 14,  6,  8],
        [ 7, 10,  4,  4, 15],
        [ 4, 17, 15, 18,  6]])

In [26]:
A - B

matrix([[-1,  0, -2, -8, -2],
        [ 0,  2,  0, -6,  6],
        [ 5, -4,  2, -2, -1],
        [-2, -1,  1,  0,  2]])

In [ ]:
A * B #会报错，矩阵乘法，A的行数与B的列数应该相等

In [27]:
a = np.mat(np.random.randint(10,size=(20)).reshape(4,5))
b = np.mat(np.random.randint(10,size=(20)).reshape(5,4))

In [28]:
a

matrix([[8, 6, 4, 4, 8],
        [9, 5, 6, 0, 7],
        [3, 2, 7, 9, 3],
        [8, 5, 1, 2, 6]])

In [29]:
b

matrix([[0, 4, 7, 4],
        [8, 5, 7, 2],
        [7, 0, 0, 1],
        [5, 0, 6, 7],
        [0, 8, 6, 5]])

In [30]:
a * b

matrix([[ 96, 126, 170, 116],
        [ 82, 117, 140,  87],
        [110,  46, 107, 101],
        [ 57, 105, 139,  87]])

# Array常见函数

In [31]:
a = np.random.randint(10,size=(20)).reshape(4,5)

In [34]:
a

array([[8, 8, 7, 6, 0],
       [7, 3, 6, 5, 4],
       [5, 1, 2, 5, 9],
       [4, 6, 4, 8, 2]])

In [32]:
np.unique(a)# 返回数组中唯一的值

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
sum(a) # 列的和

array([24, 18, 19, 24, 15])

In [36]:
sum(a[0]) # 求某一行的和

29

In [38]:
sum(a[:,0]) #某一列的和

24

In [39]:
a.max()

9

In [40]:
max(a[0]) #行的最大值

8

In [42]:
max(a[:,2])#列的最大值

7